### PR TITLE
fix: use host when using redirecting

### LINKED ISSUE #1: I tried to use this and if I visit the site without https but with http it forwards to localhost?
I tried to use this and if I visit the site without https but with http it forwards to localhost?

can anyone help?

### PR DESCRIPTION
**Pull request by raszi**
Fixes #1

### CODE REVIEW

**Comment by ChuckJonas** [comment]
Thanks! will try to test and release this by end of week

**Comment by raszi** [comment]
The code could be also cleaned up a bit (unused variables), etc. If you don't mind I would also fix that in a separate PR.

**Comment by ChuckJonas** [comment]
@raszi reviewing the code.  I have two questions:

If you look at the comment on the `request.headers` object it says:

```
Returns a Headers object consisting of the headers associated with request. Note that headers added in the network layer by the user agent will not be accounted for in this object, e.g., the "Host" header.
```

Based on that, it seems like `host` isn't added to the header?

My second question is if it's really safe to trust the `req.headers.host` for this redirect?  I seems like there might be some [way to abuse this](https://www.acunetix.com/blog/articles/automated-detection-of-host-header-attacks/#:~:text=The%20host%20header%20specifies%20which,to%20as%20a%20virtual%20host.).

**Comment by ChuckJonas** [comment]
Adding additional links for research...

https://github.com/vercel/next.js/issues/36625

https://github.com/vercel/next.js/issues/37536

so it seems that since `12.0.8` that the hostname is overwritten by localhost.  It can be set by providing an env for `hostname`.  

However, this doesn't work with sites that are responding to requests from multiple domains.

I wonder if the solution might be to add an optional ability to whitelist domains... then we can trust `host` header. 

Although, not sure what we would do if the whitelist match is missed

**Comment by raszi** [comment]
I am not sure I understood what you mean here. This is the way how HTTP works. If your User-Agent requests a URL for e.g. `http://example.com/` then it will issue the following request to the server:

```
GET / HTTP/1.1   
Host: example.com                                                                                                                                                                                             

```

Of course, there could be additional headers. But the [`Host`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Host) header is always set by the User-Agent (at least for HTTP/1.1 requests). The modification that I did is just using that `Host` header to do the redirection. So if the request was issued as `http://foobar.com/` then this middleware will redirect that to `https://foobar.com/`.

You can try to be super safe and do a whitelist of hostnames as you mentioned, but I don't think it is worth the effort. What can an attacker achieve with such a formed request? They'll get a redirection to the provided hostname with https protocol, and so what? :)

**Comment by ChuckJonas** [comment]
> You can try to be super safe and do a whitelist of hostnames as you mentioned, but I don't think it is worth the effort. What can an attacker achieve with such a formed request? They'll get a redirection to the provided hostname with https protocol, and so what? :)

I'm not sure for all the use cases this could be used, but I'd guess there's one where a host header attack could be impactful. 

Although, I'd guess the current implementation using `nexturl` is also vulnerable. Eitherway, I think the solution is to add an optional "allow list" to let people decide if the extra configuration is worth it.  

Published this fix in 0.1.4

**Pull request merged**
